#ifndef OPERSERV_H
#define OPERSERV_H

#define OS_HELP_SHORT 1
#define OS_HELP_LONG 2
#define OS_MOD_HELP_SHORT 3
#define OS_MOD_HELP_LONG 4
#define OS_RAW_HELP_SHORT 5
#define OS_RAW_HELP_LONG 6
#define OS_GLOBAL_HELP_SHORT 7
#define OS_GLOBAL_HELP_LONG 8
#define OS_ADMIN_HELP_SHORT 9
#define OS_ADMIN_HELP_LONG 10
#define OS_SESSION_HELP_SHORT 11
#define OS_SESSION_HELP_LONG 12
#define OS_AKILL_HELP_SHORT 13
#define OS_AKILL_HELP_LONG 14
#define OS_EXCEPTIONS_HELP_SHORT 15
#define OS_EXCEPTIONS_HELP_LONG 16
#define OS_JUPE_HELP_SHORT 17
#define OS_JUPE_HELP_LONG 18
#define OS_SET_HELP_SHORT 19
#define OS_SET_HELP_LONG 20
#define OS_SHUTDOWN_HELP_SHORT 21
#define OS_SHUTDOWN_HELP_LONG 22
#define OS_QUARENTINE_HELP_SHORT 23
#define OS_QUARENTINE_HELP_LONG 24

#endif
